export const ICONS = {
  IconShopping: "fa-solid fa-bag-shopping",
  IconGroceries: "fa-solid fa-cart-shopping",
  IconEntertainment: "fa-solid fa-gamepad",
  IconCar: "fa-solid fa-car",
  IconTransport: "fa-solid fa-train",
  IconHealth: "fa-solid fa-suitcase-medical",
  IconUtilities: "fa-solid fa-plug",
  IconEducation: "fa-solid fa-book",
  IconTravel: "fa-solid fa-umbrella-beach",
  IconDining: "fa-solid fa-utensils",
  IconGifts: "fa-solid fa-gift",
  IconSalary: "fa-solid fa-sack-dollar",
  IconHome: "fa-solid fa-house",
  IconPersonalCare: "fa-solid fa-bath",
  IconClothing: "fa-solid fa-shirt",
  IconPhoneInternet: "fa-solid fa-phone",
  IconTaxes: "fa-solid fa-money-bill",
  IconMiscellaneous: "fa-solid fa-question"
};
